# Generated by Django 5.2.14 on 2026-08-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_abouthero_aboutitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('paragraph_1', models.TextField(blank=True, null=True)),
                ('paragraph_2', models.TextField(blank=True, null=True)),
                ('paragraph_3', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadershipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('icon_name', models.CharField(default='Briefcase', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_text', models.TextField()),
                ('mission_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StatCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AboutHero',
        ),
        migrations.DeleteModel(
            name='AboutItem',
        ),
    ]
